<?php

namespace BaseX;

use BaseX\Error\ImportError;
use BaseX\Error\ResultMapperError;
use BaseX\Error\SessionError;
use BaseX\Error\SocketError;
use BaseX\Error\UnserializationError;

/**
 * Test class for Error.
 * Generated by PHPUnit on 2012-10-14 at 23:16:34.

 */
class ErrorTest extends \PHPUnit_Framework_TestCase {
  
  /**
   * @expectedException BaseX\Error
   */
  function testError() {
    throw new \BaseX\Error();
  }
  
  /**
   * @expectedException BaseX\Error\SessionError
   */
  function testSessionError() {
    throw new SessionError;
  }
  /**
   * @expectedException BaseX\Error\SocketError
   */
  function testSocketError() {
    throw new SocketError;
  }
  /**
   * @expectedException BaseX\Error\ResultMapperError
   */
  function testResultError() {
    throw new ResultMapperError;
  }
  /**
   * @expectedException BaseX\Error\UnserializationError
   */
  function testSerialError() {
    throw new UnserializationError;
  }
  /**
   * @expectedException BaseX\Error\ImportError
   */
  function testImportError() {
    throw new ImportError;
  }
}
