<?php

namespace BaseX\Resource\Iterator;

use BaseX\PHPUnit\TestCaseDb;

use BaseX\Database;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-21 at 14:42:23.
 */
class ResourcesTest extends TestCaseDb
{

  /**
   * @var Resources
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    parent::setUp();
    $this->object = new Resources($this->db);
    $this->db->store('test.txt', 'test');
    $this->db->add('test.xml', '<test/>');
    $this->db->add('test/test.xml', '<test/>');
    $this->db->add('sa/test.xml', '<test/>');
    $this->db->add('test/path/test.xml', '<test/>');
    
  }

 

  /**
   * @covers BaseX\Resource\Iterator\Resources::setPath
   */
  public function testSetPath()
  {
     $this->object->setPath('test');
    
    $this->assertEquals(2, $this->object->getIterator()->count());
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::exclude
   * @todo   Implement testExclude().
   */
  public function testExclude()
  {
    $this->object->exclude('@^test/.*@');
    
    $this->assertEquals(3, $this->object->getIterator()->count());
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::withTimestamps
   */
  public function testWithTimestamps()
  {
    foreach ($this->object->withTimestamps() as $resource)
    {
       $this->assertTrue($resource instanceof \BaseX\Resource);
       $this->assertNotNull($resource->getModified());
    }
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::bySize
   * @todo   Implement testBySize().
   */
  public function testBySize()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::byModified
   * @todo   Implement testByModified().
   */
  public function testByModified()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::byContentType
   * @todo   Implement testByContentType().
   */
  public function testByContentType()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::byPath
   * @todo   Implement testByPath().
   */
  public function testByPath()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::byType
   * @todo   Implement testByType().
   */
  public function testByType()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::reverse
   * @todo   Implement testReverse().
   */
  public function testReverse()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::setConverter
   * @todo   Implement testSetConverter().
   */
  public function testSetConverter()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::getIterator
   */
  public function testGetIterator()
  {
    foreach ($this->object as $resource)
    {
      $this->assertTrue($resource instanceof \BaseX\Resource);
    }
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::convertResource
   * @todo   Implement testConvertResource().
   */
  public function testConvertResource()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\Resources::begin
   * @todo   Implement testBegin().
   */
  public function testBegin()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
