<?php

namespace BaseX\Resource\Iterator;

use BaseX\PHPUnit\TestCaseDb;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-20 at 21:50:13.
 */
class ResourceIteratorTest extends TestCaseDb
{

  /**
   * @var ResourceIterator
   */
  protected $iterator;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    parent::setUp();
    $this->iterator = new ResourceIterator($this->db, '');
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::get
   */
  public function testGet()
  {
    $this->db->add('te st.xml', '<test/>');
    $this->db->add('fo/ld/e r/te st.xml', '<test/>');
    $this->assertEquals(2, $this->iterator->count());
    $this->assertTrue($this->iterator->get(0) instanceof \BaseX\Resource\Document);
    foreach ($this->iterator as $i)
    {
      $this->assertTrue($i instanceof \BaseX\Resource\Document);
    }
  }
  
  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::get
   */
  public function testGetEmpty()
  {
    foreach ($this->iterator as $i)
    {
      $this->assertTrue(false);
    }
    $this->assertNull($this->iterator->get(1));
    
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::current
   * @todo   Implement testCurrent().
   */
  public function testCurrent()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::key
   * @todo   Implement testKey().
   */
  public function testKey()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::next
   * @todo   Implement testNext().
   */
  public function testNext()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::rewind
   * @todo   Implement testRewind().
   */
  public function testRewind()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::valid
   * @todo   Implement testValid().
   */
  public function testValid()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::count
   * @todo   Implement testCount().
   */
  public function testCount()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::getFirst
   * @todo   Implement testGetFirst().
   */
  public function testGetFirst()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::getLast
   * @todo   Implement testGetLast().
   */
  public function testGetLast()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::getSingle
   * @todo   Implement testGetSingle().
   */
  public function testGetSingle()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::bySize
   * @todo   Implement testBySize().
   */
  public function testBySize()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::byModified
   * @todo   Implement testByModified().
   */
  public function testByModified()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::byContentType
   * @todo   Implement testByContentType().
   */
  public function testByContentType()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::byPath
   * @todo   Implement testByPath().
   */
  public function testByPath()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::byType
   * @todo   Implement testByType().
   */
  public function testByType()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Resource\Iterator\ResourceIterator::reverse
   * @todo   Implement testReverse().
   */
  public function testReverse()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
