<?php

namespace BaseX\Dav\Iterator;

use BaseX\PHPUnit\TestCaseDb;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-21 at 21:25:18.
 */
class NodesTest extends TestCaseDb
{

  /**
   * @var Nodes
   */
  protected $nodes;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    parent::setUp();
    $this->nodes = new Nodes($this->db, 'path');
    $this->db->store('test.txt', 'test');
    $this->db->add('test.xml', '<test/>');
    $this->db->add('test/test.xml', '<test/>');
    $this->db->add('test/.protect/hidden.xml', '<test/>');
    $this->db->add('test/test.xml', '<test/>');
    $this->db->add('sa/test.xml', '<test/>');
    $this->db->add('test/path/test.xml', '<test/>');
  }

 

  /**
   * @covers BaseX\Dav\Iterator\Nodes::denormalize
   * @todo   Implement testDenormalize().
   */
  public function testDenormalize()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
