<?php

namespace BaseX\Symfony\Security;

require_once dirname(__FILE__) . '/../../../../../src/BaseX/Symfony/Security/User.php';

/**
 * Test class for User.
 * Generated by PHPUnit on 2012-10-14 at 23:20:43.
 */
class UserTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var User
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new User;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers BaseX\Symfony\Security\User::isCredentialsNonExpired
   * @todo Implement testIsCredentialsNonExpired().
   */
  public function testIsCredentialsNonExpired() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::isEnabled
   * @todo Implement testIsEnabled().
   */
  public function testIsEnabled() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::isAccountNonExpired
   * @todo Implement testIsAccountNonExpired().
   */
  public function testIsAccountNonExpired() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::isAccountNonLocked
   * @todo Implement testIsAccountNonLocked().
   */
  public function testIsAccountNonLocked() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::eraseCredentials
   * @todo Implement testEraseCredentials().
   */
  public function testEraseCredentials() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::setPassword
   * @todo Implement testSetPassword().
   */
  public function testSetPassword() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::getPassword
   * @todo Implement testGetPassword().
   */
  public function testGetPassword() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::getRoles
   * @todo Implement testGetRoles().
   */
  public function testGetRoles() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::setRoles
   * @todo Implement testSetRoles().
   */
  public function testSetRoles() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::getUsername
   * @todo Implement testGetUsername().
   */
  public function testGetUsername() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::lock
   * @todo Implement testLock().
   */
  public function testLock() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::unlock
   * @todo Implement testUnlock().
   */
  public function testUnlock() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::disable
   * @todo Implement testDisable().
   */
  public function testDisable() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::enable
   * @todo Implement testEnable().
   */
  public function testEnable() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::setExpires
   * @todo Implement testSetExpires().
   */
  public function testSetExpires() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::setUsername
   * @todo Implement testSetUsername().
   */
  public function testSetUsername() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::getSalt
   * @todo Implement testGetSalt().
   */
  public function testGetSalt() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::setSalt
   * @todo Implement testSetSalt().
   */
  public function testSetSalt() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::getLastLogin
   * @todo Implement testGetLastLogin().
   */
  public function testGetLastLogin() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::setLastLogin
   * @todo Implement testSetLastLogin().
   */
  public function testSetLastLogin() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::serialize
   * @todo Implement testSerialize().
   */
  public function testSerialize() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::unserialize
   * @todo Implement testUnserialize().
   */
  public function testUnserialize() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Symfony\Security\User::__toString
   * @todo Implement test__toString().
   */
  public function test__toString() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
