<?php

namespace BaseX\Database;

use BaseX\PHPUnit\TestCaseDb;
use BaseX\Database\BackupProvider;

/**
 * Test class for BackupProvider.
 * Generated by PHPUnit on 2012-10-14 at 22:16:24.
 */
class BackupProviderTest extends TestCaseDb {

  /**
   * @var BackupProvider
   */
  protected $provider;

  
  /**
   * @covers BaseX\Database\BackupProvider::supportsType
   * @todo Implement testSupportsType().
   */
  public function testSupportsType() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Database\BackupProvider::getResult
   * @todo Implement testGetResult().
   */
  public function testGetResult() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers BaseX\Database\BackupProvider::get
   */
  public function testGet() {
    $p = new BackupProvider($this->db);
   
    $this->assertEmpty($p->get());
    $this->session->execute("CREATE BACKUP $this->db");
    $this->assertNotEmpty($p->get());
    $b = $p->get();
    $this->assertInstanceOf('BaseX\Database\Backup', $b[0]);
   
  }

}
